version: 2
jobs:
  build:
    docker:
    #  - image: circleci/openjdk:8-jdk
      - image: circleci/selenium/standalone-chrome:3.1.0

    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log selenium.log
          background: true
      
    #  - run: sudo apt-get install libgconf-2-4 
      
   #   - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
   #   - run: sudo dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
   #   

      
      - run: curl -O http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip           
      - run: ls      
      - run: unzip chromedriver_linux64
      - run: ls -lrt
      - run: chmod +x chromedriver 
      - run: ls -lrt
      - run: mv chromedriver webdriver/      
      - run: ls
      - run: pwd
      - run: mvn dependency::go-offline #make sure all dependencies are in local before going offline
      - run: mvn clean test
     
      - store_test_results:
          path: target/surefire-reports
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
