version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log selenium.log
          background: true
      #- run: mvn dependency::go-offline #make sure all dependencies are in local before going offline
      - run: mvn clean test
      - run: ls
      - run: cd webdriver/
      - run: ls
     # - run: mvn clean test
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
